language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

before_install:
  - 'useradd --no-create-home --no-user-group BottleUser'
  - 'echo BottleUser:iambottle | chpasswd'

install:
  - "pipenv install --dev"

script:
  - "pipenv run pytest"
