sudo: required
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

before_install:
  - 'useradd --no-create-home --no-user-group BottleUser'
  - 'echo BottleUser:iambottle | chpasswd'
  - 'openssl req -new -x509 -days 365 -nodes -out cacert.pem -keyout privkey.pem -subj "/C=AA/ST=State/L=Location/O=IT/CN=bottle-ssl.com"'

install:
  - "pipenv install --dev"

script:
  - "pipenv run pytest"
