sudo: required
language: python
python:
  - '2.7'
  - '3.5'
  - '3.6'

before_install:
  - 'sudo useradd --no-create-home --no-user-group BottleUser'
  - 'echo BottleUser:iambottle | sudo chpasswd'
  - 'openssl req -new -x509 -days 365 -nodes -out cacert.pem -keyout privkey.pem -subj "/C=AA/ST=State/L=Location/O=IT/CN=bottle-ssl.com"'

install:
  - 'pip install pipenv'
  - 'pipenv install --dev'
#  - 'pipenv lock -r 2>/dev/null | sudo -H pip install -U -r /dev/stdin' 

script:
   - 'pytest'
#  - 'sudo python -m pytest'
